export const userPlans = {
  free: {
    id: "free",
    name: "Gratuit",
    nameEn: "Free",
    price: 0,
    currency: "CAD",
    interval: "month",
    features: [
      "Recherche et filtrage d'événements",
      "Inscription aux événements publics",
      "Publication d'événements ouverts",
      "Rejoindre des groupes existants",
      "Notifications de base",
    ],
    featuresEn: [
      "Search and filter events",
      "Register for public events",
      "Publish open events",
      "Join existing groups",
      "Basic notifications",
    ],
  },
  premium: {
    id: "premium",
    name: "Premium",
    nameEn: "Premium",
    price: 4.99,
    currency: "CAD",
    interval: "month",
    popular: true,
    features: [
      "Toutes les fonctionnalités gratuites",
      "Créer et animer des groupes d'intérêt",
      "Alertes prioritaires personnalisées",
      "Accès anticipé aux événements populaires",
      "Événements exclusifs premium",
      "Support prioritaire",
    ],
    featuresEn: [
      "All free features",
      "Create and manage interest groups",
      "Priority personalized alerts",
      "Early access to popular events",
      "Exclusive premium events",
      "Priority support",
    ],
  },
} as const

export const organizerPlans = {
  basic: {
    id: "basic",
    name: "Commission",
    nameEn: "Commission",
    price: 0,
    currency: "CAD",
    interval: "month",
    commission: "5-10%",
    features: [
      "Publication d'événements illimitée",
      "Gestion de base des inscriptions",
      "Commission de 5-10% sur les ventes",
      "Support standard",
    ],
    featuresEn: [
      "Unlimited event publishing",
      "Basic registration management",
      "5-10% commission on sales",
      "Standard support",
    ],
  },
  sponsored: {
    id: "sponsored",
    name: "Visibilité Sponsorisée",
    nameEn: "Sponsored Visibility",
    price: 35,
    currency: "CAD",
    interval: "campaign",
    priceRange: "20-50",
    features: [
      "Mise en avant ciblée par quartier",
      "Promotion par catégorie d'âge",
      "Ciblage par type d'activité",
      "Durée de campagne flexible",
      "Statistiques de performance",
    ],
    featuresEn: [
      "Targeted promotion by neighborhood",
      "Age category promotion",
      "Activity type targeting",
      "Flexible campaign duration",
      "Performance statistics",
    ],
  },
  pro: {
    id: "pro",
    name: "Organisateur Pro",
    nameEn: "Pro Organizer",
    price: 39,
    currency: "CAD",
    interval: "month",
    priceRange: "29-49",
    popular: true,
    features: [
      "Toutes les fonctionnalités de base",
      "Outils statistiques avancés",
      "Programmation d'événements récurrents",
      "Page organisateur personnalisée",
      "Publications illimitées",
      "Support prioritaire",
      "Commission réduite (3-5%)",
    ],
    featuresEn: [
      "All basic features",
      "Advanced analytics tools",
      "Recurring event scheduling",
      "Custom organizer page",
      "Unlimited publications",
      "Priority support",
      "Reduced commission (3-5%)",
    ],
  },
} as const

export type UserPlan = keyof typeof userPlans
export type OrganizerPlan = keyof typeof organizerPlans
